spring:
  # Datasource
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  # H2
  h2:
    console:
      enabled: true
  # JPA
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace